plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yoonho.habitus'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yoonho.habitus'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
