plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yoonho.mandabit'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yoonho.mandabit'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '0.5.0'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.credentials:credentials:1.3.0'
    implementation 'androidx.credentials:credentials-play-services-auth:1.3.0'
    implementation 'com.google.android.libraries.identity.googleid:googleid:1.1.1'
}
